# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.6)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.21)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget ext_lz4)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target ext_lz4
add_library(ext_lz4 STATIC IMPORTED)

set_target_properties(ext_lz4 PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "P:/mysql-connector-cpp/cdk/extra/lz4"
)

# Import target "ext_lz4" for configuration "Debug"
set_property(TARGET ext_lz4 APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(ext_lz4 PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "P:/mysql-connector-cpp/_build/cdk/protocol/mysqlx/lz4/Debug/lz4.lib"
  )

# Import target "ext_lz4" for configuration "Release"
set_property(TARGET ext_lz4 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ext_lz4 PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "P:/mysql-connector-cpp/_build/cdk/protocol/mysqlx/lz4/Release/lz4.lib"
  )

# Import target "ext_lz4" for configuration "MinSizeRel"
set_property(TARGET ext_lz4 APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(ext_lz4 PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "C"
  IMPORTED_LOCATION_MINSIZEREL "P:/mysql-connector-cpp/_build/cdk/protocol/mysqlx/lz4/MinSizeRel/lz4.lib"
  )

# Import target "ext_lz4" for configuration "RelWithDebInfo"
set_property(TARGET ext_lz4 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(ext_lz4 PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "P:/mysql-connector-cpp/_build/cdk/protocol/mysqlx/lz4/RelWithDebInfo/lz4.lib"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
