set(PROTOBUF_INCLUDE_DIR "P:/mysql-connector-cpp/cdk/extra/protobuf/protobuf-3.11.4/src")

# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.6)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.21)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget pb_libprotobuf-lite pb_libprotobuf pb_protoc)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target pb_libprotobuf-lite
add_library(pb_libprotobuf-lite STATIC IMPORTED)

set_target_properties(pb_libprotobuf-lite PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "P:/mysql-connector-cpp/cdk/extra/protobuf/protobuf-3.11.4/src"
)

# Create imported target pb_libprotobuf
add_library(pb_libprotobuf STATIC IMPORTED)

set_target_properties(pb_libprotobuf PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "P:/mysql-connector-cpp/cdk/extra/protobuf/protobuf-3.11.4/src"
)

# Create imported target pb_protoc
add_executable(pb_protoc IMPORTED)

# Import target "pb_libprotobuf-lite" for configuration "Debug"
set_property(TARGET pb_libprotobuf-lite APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(pb_libprotobuf-lite PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX;RC"
  IMPORTED_LOCATION_DEBUG "P:/mysql-connector-cpp/_build/cdk/protocol/mysqlx/protobuf/protobuf-3.11.4/cmake/Debug/libprotobuf-lited.lib"
  )

# Import target "pb_libprotobuf" for configuration "Debug"
set_property(TARGET pb_libprotobuf APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(pb_libprotobuf PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX;RC"
  IMPORTED_LOCATION_DEBUG "P:/mysql-connector-cpp/_build/cdk/protocol/mysqlx/protobuf/protobuf-3.11.4/cmake/Debug/libprotobufd.lib"
  )

# Import target "pb_protoc" for configuration "Debug"
set_property(TARGET pb_protoc APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(pb_protoc PROPERTIES
  IMPORTED_LOCATION_DEBUG "P:/mysql-connector-cpp/_build/cdk/protocol/mysqlx/protobuf/runtime_output_directory/Debug/protoc.exe"
  )

# Import target "pb_libprotobuf-lite" for configuration "Release"
set_property(TARGET pb_libprotobuf-lite APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(pb_libprotobuf-lite PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX;RC"
  IMPORTED_LOCATION_RELEASE "P:/mysql-connector-cpp/_build/cdk/protocol/mysqlx/protobuf/protobuf-3.11.4/cmake/Release/libprotobuf-lite.lib"
  )

# Import target "pb_libprotobuf" for configuration "Release"
set_property(TARGET pb_libprotobuf APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(pb_libprotobuf PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX;RC"
  IMPORTED_LOCATION_RELEASE "P:/mysql-connector-cpp/_build/cdk/protocol/mysqlx/protobuf/protobuf-3.11.4/cmake/Release/libprotobuf.lib"
  )

# Import target "pb_protoc" for configuration "Release"
set_property(TARGET pb_protoc APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(pb_protoc PROPERTIES
  IMPORTED_LOCATION_RELEASE "P:/mysql-connector-cpp/_build/cdk/protocol/mysqlx/protobuf/runtime_output_directory/Release/protoc.exe"
  )

# Import target "pb_libprotobuf-lite" for configuration "MinSizeRel"
set_property(TARGET pb_libprotobuf-lite APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(pb_libprotobuf-lite PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX;RC"
  IMPORTED_LOCATION_MINSIZEREL "P:/mysql-connector-cpp/_build/cdk/protocol/mysqlx/protobuf/protobuf-3.11.4/cmake/MinSizeRel/libprotobuf-lite.lib"
  )

# Import target "pb_libprotobuf" for configuration "MinSizeRel"
set_property(TARGET pb_libprotobuf APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(pb_libprotobuf PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX;RC"
  IMPORTED_LOCATION_MINSIZEREL "P:/mysql-connector-cpp/_build/cdk/protocol/mysqlx/protobuf/protobuf-3.11.4/cmake/MinSizeRel/libprotobuf.lib"
  )

# Import target "pb_protoc" for configuration "MinSizeRel"
set_property(TARGET pb_protoc APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(pb_protoc PROPERTIES
  IMPORTED_LOCATION_MINSIZEREL "P:/mysql-connector-cpp/_build/cdk/protocol/mysqlx/protobuf/runtime_output_directory/MinSizeRel/protoc.exe"
  )

# Import target "pb_libprotobuf-lite" for configuration "RelWithDebInfo"
set_property(TARGET pb_libprotobuf-lite APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(pb_libprotobuf-lite PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX;RC"
  IMPORTED_LOCATION_RELWITHDEBINFO "P:/mysql-connector-cpp/_build/cdk/protocol/mysqlx/protobuf/protobuf-3.11.4/cmake/RelWithDebInfo/libprotobuf-lite.lib"
  )

# Import target "pb_libprotobuf" for configuration "RelWithDebInfo"
set_property(TARGET pb_libprotobuf APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(pb_libprotobuf PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX;RC"
  IMPORTED_LOCATION_RELWITHDEBINFO "P:/mysql-connector-cpp/_build/cdk/protocol/mysqlx/protobuf/protobuf-3.11.4/cmake/RelWithDebInfo/libprotobuf.lib"
  )

# Import target "pb_protoc" for configuration "RelWithDebInfo"
set_property(TARGET pb_protoc APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(pb_protoc PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "P:/mysql-connector-cpp/_build/cdk/protocol/mysqlx/protobuf/runtime_output_directory/RelWithDebInfo/protoc.exe"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
